rvm: 2.2

sudo: required
services: docker

before_install: curl -L https://www.getchef.com/chef/install.sh | sudo bash -s -- -P chefdk -v 0.9.0
install: bundle install

before_script: sudo iptables -L DOCKER || sudo iptables -N DOCKER

script:
  - bundle exec rake
  # Run test-kitchen with docker driver, for example:
  - bundle exec rake 'integration:docker[/^community$/,test]'
